# Generated by Django 4.1.4 on 2023-01-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(max_length=50, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название манги')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_part.genre')),
                ('type_of_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_part.type_of_manga', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Комменатрии')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga_part.manga')),
            ],
        ),
    ]
