# Generated by Django 4.1.4 on 2023-01-02 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga_part', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='manga',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='manga_part.manga'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
